# Generated by Django 2.2.5 on 2021-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_crop_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='fertilizer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
