# Generated by Django 2.2.5 on 2021-03-06 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_crop_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='prepare_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
