# Generated by Django 2.2.5 on 2021-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_crop_prepare_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='fertilizer',
            new_name='fertilizer_name',
        ),
        migrations.AddField(
            model_name='crop',
            name='fertilizer_quantity',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
